/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  SmockFacet2,
  SmockFacet2Interface,
} from "../../../../src/contracts/test/SmockFacet2";

const _abi = [
  {
    inputs: [],
    name: "getNewStructValueFromExtended",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getOldStructValueFromExtended",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061018b806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806336d0c1d0146100465780638129fc1c14610064578063f6af19c01461006e575b600080fd5b61004e61008c565b60405161005b919061013a565b60405180910390f35b61006c6100ac565b005b6100766100d2565b604051610083919061013a565b60405180910390f35b60006100966100f2565b60000160009054906101000a900460ff16905090565b60016100b66100f2565b60040160006101000a81548160ff021916908315150217905550565b60006100dc6100f2565b60040160009054906101000a900460ff16905090565b6000807f67301b4e5cd5524778597dc615896d3b917dbc55199870fdeb8c8cb13d6fa0de90508091505090565b60008115159050919050565b6101348161011f565b82525050565b600060208201905061014f600083018461012b565b9291505056fea2646970667358221220ce080cef38bc6c55fbf34365df8046b19c5e9b107598232e5b14e2547ef6d06664736f6c634300080e0033";

type SmockFacet2ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SmockFacet2ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SmockFacet2__factory extends ContractFactory {
  constructor(...args: SmockFacet2ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<SmockFacet2> {
    return super.deploy(overrides || {}) as Promise<SmockFacet2>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): SmockFacet2 {
    return super.attach(address) as SmockFacet2;
  }
  override connect(signer: Signer): SmockFacet2__factory {
    return super.connect(signer) as SmockFacet2__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SmockFacet2Interface {
    return new utils.Interface(_abi) as SmockFacet2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SmockFacet2 {
    return new Contract(address, _abi, signerOrProvider) as SmockFacet2;
  }
}
