/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { GeneralEvent, GeneralEventInterface } from "../GeneralEvent";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Deployed",
    type: "event",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220580bf8d97e7eaa9427c33bb612bdd46b3712738d9e58fede8dfce44a571657bf64736f6c634300080b0033";

type GeneralEventConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GeneralEventConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GeneralEvent__factory extends ContractFactory {
  constructor(...args: GeneralEventConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "GeneralEvent";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<GeneralEvent> {
    return super.deploy(overrides || {}) as Promise<GeneralEvent>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): GeneralEvent {
    return super.attach(address) as GeneralEvent;
  }
  connect(signer: Signer): GeneralEvent__factory {
    return super.connect(signer) as GeneralEvent__factory;
  }
  static readonly contractName: "GeneralEvent";
  public readonly contractName: "GeneralEvent";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GeneralEventInterface {
    return new utils.Interface(_abi) as GeneralEventInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GeneralEvent {
    return new Contract(address, _abi, signerOrProvider) as GeneralEvent;
  }
}
