/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
import type * as eventsSol from './Events.sol';
export type { eventsSol };
import type * as interfaces from './interfaces';
export type { interfaces };
export type { Vault } from './Vault';
