/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from 'ethers';
import type { Provider, TransactionRequest } from '@ethersproject/providers';
import type { PromiseOrValue } from '../../../../../../common';
import type {
  ProxyConnector,
  ProxyConnectorInterface,
} from '../../../../../../src/contracts/core/test/redstone/ProxyConnector';

const _abi = [
  {
    inputs: [],
    name: 'CalldataMustHaveValidPayload',
    type: 'error',
  },
  {
    inputs: [],
    name: 'CalldataOverOrUnderFlow',
    type: 'error',
  },
  {
    inputs: [],
    name: 'EachSignerMustProvideTheSameValue',
    type: 'error',
  },
  {
    inputs: [],
    name: 'EmptyCalldataPointersArr',
    type: 'error',
  },
  {
    inputs: [],
    name: 'IncorrectUnsignedMetadataSize',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'receivedSignersCount',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'requiredSignersCount',
        type: 'uint256',
      },
    ],
    name: 'InsufficientNumberOfUniqueSigners',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidCalldataPointer',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'bytes',
        name: 'result',
        type: 'bytes',
      },
    ],
    name: 'ProxyCalldataFailedWithCustomError',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'string',
        name: 'message',
        type: 'string',
      },
    ],
    name: 'ProxyCalldataFailedWithStringMessage',
    type: 'error',
  },
  {
    inputs: [],
    name: 'ProxyCalldataFailedWithoutErrMsg',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'receivedSigner',
        type: 'address',
      },
    ],
    name: 'SignerNotAuthorised',
    type: 'error',
  },
] as const;

const _bytecode =
  '0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220c29d25ce76b99b51700b8c62b02225159b2c76ba584580d5ed05eb31377de23a64736f6c63430008150033';

type ProxyConnectorConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (xs: ProxyConnectorConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
  xs.length > 1;

export class ProxyConnector__factory extends ContractFactory {
  constructor(...args: ProxyConnectorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = 'ProxyConnector';
  }

  override deploy(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ProxyConnector> {
    return super.deploy(overrides || {}) as Promise<ProxyConnector>;
  }
  override getDeployTransaction(overrides?: Overrides & { from?: PromiseOrValue<string> }): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ProxyConnector {
    return super.attach(address) as ProxyConnector;
  }
  override connect(signer: Signer): ProxyConnector__factory {
    return super.connect(signer) as ProxyConnector__factory;
  }
  static readonly contractName: 'ProxyConnector';

  public readonly contractName: 'ProxyConnector';

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ProxyConnectorInterface {
    return new utils.Interface(_abi) as ProxyConnectorInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): ProxyConnector {
    return new Contract(address, _abi, signerOrProvider) as ProxyConnector;
  }
}
