/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type {
  IMintFacet,
  IMintFacetInterface,
} from '../../../../../../src/contracts/core/minter/interfaces/IMintFacet';

const _abi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: '_account',
        type: 'address',
      },
      {
        internalType: 'address',
        name: '_kreskoAsset',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '_mintAmount',
        type: 'uint256',
      },
    ],
    name: 'mintKreskoAsset',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;

export class IMintFacet__factory {
  static readonly abi = _abi;
  static createInterface(): IMintFacetInterface {
    return new utils.Interface(_abi) as IMintFacetInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IMintFacet {
    return new Contract(address, _abi, signerOrProvider) as IMintFacet;
  }
}
