/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
import type * as kiss from "./kiss";
export type { kiss };
import type * as kreskoasset from "./kreskoasset";
export type { kreskoasset };
import type * as minter from "./minter";
export type { minter };
import type * as shared from "./shared";
export type { shared };
import type * as staking from "./staking";
export type { staking };
import type * as test from "./test";
export type { test };
import type * as vendor from "./vendor";
export type { vendor };
