/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
export type { AuthEvent } from './AuthEvent';
export type { DiamondEvent } from './DiamondEvent';
export type { StakingEvent } from './StakingEvent';
